# This file stores secrets and configuration for the Streamlit app.
# Learn more at https://docs.streamlit.io/library/advanced-features/secrets-management

# The base URL of the local LLM server (Ollama, LM Studio, etc.)
# For Ollama, this is the default. For LM Studio, you can find this in the app.
LOCAL_LLM_URL = "http://localhost:11434/v1" 
